pub fn keywords() -> &'static [&'static str] {
    &[
        "let",
        "const",
        "function",
        "if",
        "else",
        "while",
        "for",
        "of",
        "return",
        "true",
        "false",
        "null",
        "undefined",
        "typeof",
        "try",
        "catch",
        "finally",
        "throw",
        "new",
    ]
}
